### ISSUE TITLE
Away/Home modes

### ISSUE THREAD

**Issue by AntoineGuilbaud** [sinopetechnologies/smartThings#16]
Hi there,
Is there a way to control the neviweb Away/Home mode from smartthings ?
What I want is to be able could turn on my baseboard heaters and load controller by setting the mode to "home" in the smartthings app

**Comment by SinopeTechSupport** [comment]
Hello, 

Using Smartthing you won't be able to activate the Neviweb Away and Home mode. But using the Smartthings app you will be able to recreate that feature using the automation/routine.

**Comment by AntoineGuilbaud** [comment]
Thanks,
I don't know how I'd be able to recreate that feature using the smartthings app without reimplementing an entire scheduler in ST.
What I'm interested in is to set the gateway in away mode when I leave, and in home mode (to benefit from neviweb's schedule) when I'm back.
While it's certainly possible to set the thermostats to a specific temperature from ST, doing so will set them to manual mode, with no way (that I know of) to set them back to automatic when I'm back....

Going back to my initial request, is it because of safety concerns that this feature isn't implemented ?

**Comment by gnault75** [comment]
Hi,
It used to be done from a third party. He created a presenceaway and a presencehome that could triggered from a Webcore piston in Smartthings. I could set my thermostat in Away mode individually and then on Presencehome when I get back home. 

The code has not been updated yet but here it is: https://github.com/infofiend/Sinope-Thermostat/tree/master

I would be very interested if Sinope adds that feature.

**Comment by AntoineGuilbaud** [comment]
I needed this feature so much that I decided to study the API calls made from neviweb's website, and came up with this: https://github.com/AntoineGuilbaud/smartThings/blob/master/driver_device_gateway_mode.groovy

I've been using it for 2 or 3 days now, without any issues, for my 2 locations.

You can install it the same way you install a thermostat or a load controller. (add the device from ST webpage, then fill the info in the device settings in the phone app, then add it to the list of the managed devices in the smartapp)

let me know what you think about it.

**Comment by SinopeTechSupport** [comment]
Hi Antoine,

To answer your question, this feature wasn't enabled in SmartThings by choice. Although users can control their Sinopé devices through their SmartThings account, only Neviweb can offer all control options. Neviweb is known to unleash the full potential of the smart home, which is why we offer more features in this management platform. For the moment, it is not planned to add more features to SmartThings.

Thank you,
The Sinopé Technologies team

**Comment by AntoineGuilbaud** [comment]
Ok, thanks for your answer.
Any issue with the device handler I mentioned in my previous post?

**Comment by jmbinette** [comment]
This makes no sense at all.

If Sinope wants to take a serious place in the home automation thermostats market, this cannot work.

Contribute and users will also do it and you will grow your user base by having the best product in the end.

Here you have someone that suggest something, made it work and you guys tell us that this was not implemented "by choice to promote Neviweb" ? Come on.

Don't get me wrong, I love the product and got 8 Sinope thermostats. 

Your ST device handler was always below average and now I understand why.

**Comment by gnault75** [comment]
I agree. I installed Antoine’s code and I’m very happy with the solution! Thanks for your hard work!

 I also enjoyed infofiend’s code because I could automate a +0,5 degree for several thermostats when I felt cold because of humidity.

**Comment by jfllabj** [comment]
Antoine Guilbaud

How you change mode from home to away. I see the gateway but it's still to home.

**Comment by AntoineGuilbaud** [comment]
@jfllabj 
I added a small wiki page: 
https://github.com/AntoineGuilbaud/smartThings/wiki/How-to-install-the-Gateway-Mode-Device

If you need more help with this, please open a new issue here: https://github.com/AntoineGuilbaud/smartThings/issues
