### ISSUE TITLE
Sinope Dimmer

### ISSUE THREAD

**Issue by AntoineGuilbaud** [sinopetechnologies/smartThings#3]
Hi there,
Do you plan to support the new sinope dimmer ?

If yes, I'll be happy to by some of these

**Comment by gnault75** [comment]
Bought dimmer. are you going to support it with ST?

**Comment by vpepin** [comment]
Hi @AntoineGuilbaud and @gnault75,

I am truly sorry for the delay between your questions and our answers. We will be working on adapting the switch's driver to make it compatible with the dimmer. However, I cannot provide you with a date as of now.

As soon as it becomes available, I will let you know.

Thank you for your patience and have a good day,

Vanessa Pepin
Technical support agent
Sinopé Technologies

**Comment by vpepin** [comment]
Hi @AntoineGuilbaud and @gnault75 ,

The driver for the dimmer has been added to the available drivers.

Thank you again for your patience and have a good day,

Vanessa Pepin
Technical support agent
Sinopé Technologies
