### ISSUE TITLE
Integration with thermostat and google home

### ISSUE THREAD

**Issue by jeanbeaulieu** [sinopetechnologies/smartThings#7]
Hello,

When integrating the thermostat with smartthings and trying to control it with google home it doesn't work.

Google home always says that the thermostat is off.
To fix it, I slightly modified the devicehandler.  I added the line :   sendEvent(name: "thermostatMode", value: "heat") at the end of the devicedata() fonction.

Now it works.

Jean

**Comment by vpepin** [comment]
Hi Jean,

Thank you for letting us know about this issue, and I am sorry for the delay between your comment and our answer.

I will be testing the line you have added and adding it to the driver when I confirm everything is working accordingly.

Thank you and have a good day,

Vanessa Pepin
Technical support agent
Sinopé Technologies

**Comment by vpepin** [comment]
Hi Jean,

The driver has been updated as per your suggestion for the compatibility with Google Home.

Thank you and have a good day,

Vanessa Pepin
Technical support agent
Sinopé Technologies

**Comment by sadortun** [comment]
@jeanbeaulieu are you happy with thé google home intégration ?
